# Generated by Django 4.1.4 on 2024-10-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_remove_applicantmodel_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
